---
title: KSP Part Catalog
timezone: Europe/Amsterdam
collections:
  client_collection:
    title: Pagina's inhoud
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  parts_min:
    title: Parts
    output: true
volledige-titel: KSP Part Catalog
tags: KSP Part Catalog Filter Sort
# phone: 06-12345678
# email: effie@testmail.com
description: KSP Part Catalog
url: https://ksp-part-catalog.space
enforce_ssl: ksp-part-catalog.space
github_username: bunkersem
youtube_username: 9Wereld
markdown: kramdown
theme: minima
plugins: 
author:
  name: Sem Postma
  from: Oosterhout, Noord Brabant, The Netherlands
  role: Developer
  email: sem.postma@gmail.com
designer:
  name: Sem Postma
  from: Oosterhout, Noord Brabant, The Netherlands
  role: Designer
  email: sem.postma@gmail.com
